### ISSUE TITLE
Add MTR support

### ISSUE THREAD

**Issue by winstonma** [kennyfong19931/siri-shortcut-hk-bus-eta#1]
Opendata support MTR and it would be great if MTR is supported by Siri ([API Doc](https://github.com/kirosc/telegram-hketa/tree/master/data)). 

This is a [list of stops that support ETA in JSON format](https://raw.githubusercontent.com/kirosc/telegram-hketa/master/data/routes-mtr.json), hard-coded by [@kirosc](https://github.com/kirosc/telegram-hketa/tree/master/data).

**Comment by winstonma** [comment]
Please see if it is possible to add LRT support too.

This is a [list of stops that support ETA in JSON format](https://raw.githubusercontent.com/kirosc/telegram-hketa/master/data/station-lrt.json), hard-coded by [@kirosc](https://github.com/kirosc/telegram-hketa/tree/master/data).

**Comment by winstonma** [comment]
@kennyfong19931 Thanks for updating the Siri shortcut to version 3.0

I tried to find the MTR station ETA (e.g. Yuen Long) from the Siri shortcut but have no success. May I know how could I get that?

Sorry I forgot to attach the MTR line json file. This is a [list of stops that support ETA in JSON format](https://raw.githubusercontent.com/kirosc/telegram-hketa/master/data/mtr-lines.json), hard-coded by [@kirosc](https://github.com/kirosc/telegram-hketa/tree/master/data).

**Comment by kennyfong19931** [comment]
@winstonma No plan for railway support for now
This shortcut is focused on bus/minibus eta
